def medical_chatbot(disease, user_question, confidence=None, severity=None):
    """
    Enhanced Medical Chatbot
    - Provides a detailed and professional answer in clear, easy-to-understand language
    - Uses disease, confidence, and severity for context
    - Returns a full report-style answer automatically
    """
    
    if not user_question:
        return "Please ask a question related to the detected disease."

    # Predefined detailed disease information
    disease_info = {
        "Normal": {
            "description": (
                "Based on the analysis of your X-ray or MRI image, no abnormalities were detected. "
                "This indicates that the scanned areas of the lungs, bones, or other organs appear healthy "
                "according to the AI model."
            ),
            "symptoms": (
                "Since no condition was detected, there are no specific symptoms associated. "
                "However, regular health check-ups and a balanced lifestyle are recommended to maintain good health."
            ),
            "advice": (
                "Continue with routine medical check-ups, maintain a nutritious diet, exercise regularly, "
                "avoid smoking, and monitor any unusual symptoms if they occur."
            )
        },
        "Pneumonia": {
            "description": (
                "The uploaded image shows signs consistent with pneumonia. Pneumonia is an infection "
                "that inflames the air sacs in one or both lungs, which can fill with fluid or pus. "
                "Early detection is important for effective treatment."
            ),
            "symptoms": (
                "Symptoms of pneumonia may include persistent cough with phlegm or pus, fever, chills, "
                "difficulty breathing, chest pain, fatigue, and sometimes nausea or vomiting."
            ),
            "advice": (
                "It is highly recommended to consult a healthcare professional immediately. "
                "Treatment may include antibiotics for bacterial pneumonia, rest, hydration, "
                "and careful monitoring of oxygen levels. Follow-up imaging may be required to ensure recovery."
            )
        },
        "Tuberculosis": {
            "description": (
                "The image analysis suggests signs of tuberculosis (TB). TB is a bacterial infection "
                "that primarily affects the lungs but can also involve other organs. "
                "It is contagious and requires prompt medical attention."
            ),
            "symptoms": (
                "Common symptoms include a persistent cough lasting more than three weeks, coughing up blood, "
                "unexplained weight loss, night sweats, fever, fatigue, and chest discomfort."
            ),
            "advice": (
                "It is important to consult a doctor for diagnostic tests such as a chest X-ray, "
                "sputum test, or TB skin test. Treatment typically involves a long course of antibiotics, "
                "and adherence to the prescribed regimen is crucial to ensure full recovery and to prevent spreading the infection."
            )
        }
    }

    # Fetch the disease info
    info = disease_info.get(disease, {
        "description": "No detailed information is available for this condition.",
        "symptoms": "N/A",
        "advice": "Please consult a qualified medical professional for guidance."
    })

    # Build the full detailed answer
    severity_msg = ""
    if confidence is not None and severity is not None:
        severity_msg = f"\nAI Confidence Level: {confidence}% | Estimated Severity: {severity}"

    answer = (
        "==================== DETAILED MEDICAL REPORT ====================\n\n"
        f"Detected Condition: {disease}\n"
        f"{severity_msg}\n\n"
        f"Detailed Explanation:\n{info['description']}\n\n"
        f"Common Symptoms:\n{info['symptoms']}\n\n"
        f"Recommended Actions & Advice:\n{info['advice']}\n\n"
        f"Your Question:\n{user_question}\n\n"
        "Important Notes:\n"
        "This report is generated by an AI model analyzing X-ray or MRI images. "
        "It is intended solely for informational purposes. "
        "Always consult a licensed medical professional for confirmation, accurate diagnosis, and treatment.\n"
        "================================================================="
    )

    return answer
